-- Script para crear la tabla de promociones seguras sugerida por el usuario
create table public.promociones_offszn_seguro (
  id bigint generated by default as identity not null,
  producer_id uuid not null,
  buy_quantity integer not null default 2,
  get_quantity integer not null default 1,
  discount_percent numeric(10, 2) not null default 100,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint promociones_offszn_seguro_pkey primary key (id),
  constraint promociones_offszn_seguro_producer_id_fkey foreign key (producer_id) references users (id) on delete cascade
) TABLESPACE pg_default;

-- Índice para búsquedas rápidas por productor
create index if not exists idx_promociones_producer_id on public.promociones_offszn_seguro using btree (producer_id) TABLESPACE pg_default;
